text = "It took me a long time and most of the world to learn what I kn o wabout love and fate and the choices we make, but the heart of i tcame to me in an instant, while I was chained to a wall and b e i n gtortured. I realized, somehow, through the screaming in my m i n d ,that even in that shackled, bloody helplessness, I was stillfree: free to hate the men who were torturing me, or to forgivethem. It doesn't sound like much, I know. But in the flinch a n dbite of the chain, when it's all you've got, that freedom is auniverse of possibility. And the choice you make, between hatingand forgiving, can become the story of your l i f e .In my case, it's a long story, and a crowded one. I was arevolutionary who lost his ideals in heroin, a philosopher w h olost his integrity in crime, and a poet who lost his soul in amaximum-security prison. When I escaped from that prison, o v e rthe front wall, between two gun-towers, I became my country'smost wanted man. Luck ran with me and flew with me across t h eworld to India, where I joined the Bombay mafia. I worked as agunrunner, a smuggler, and a counterfeiter. I was chained o nthree continents, beaten, stabbed, and starved. I went to war. Iran into the enemy guns. And I survived, while other men aroundme died. They were better men than I am, most of them: better m e nwhose lives were crunched up in mistakes, and thrown away by t h ewrong second of someone else's hate, or love, or indifference.And I buried them, too many of those men, and grieved theirstories and their lives into my o w n .But my story doesn't begin with them, or with the mafia: it g o e sback to that first day in Bombay. Fate put me in the game there.Luck dealt the cards that led me to Karla Saaranen. And I startedto play it out, that hand, from the first moment I looked intoher green eyes. So it begins, this story, like everything else--with a woman, and a city, and a little bit of luck.The first thing I noticed about Bombay, on that first day, w a sthe smell of the different air. I could smell it before I saw o rheard anything of India, even as I walked along the umbilicalcorridor that connected the plane to the airport. I was excitedand delighted by it, in that first Bombay minute, escaped fromprison and new to the wide world, but I didn't and couldn'trecognize it. I know now that it's the sweet, sweating smell o fhope, which is the opposite of hate; and it's the sour, stifled smell of greed, which is the opposite of love. It's the smell o fgods, demons, empires, and civilizations in resurrection a n ddecay. It's the blue skin-smell of the sea, no matter where y o uare in the Island City, and the blood-metal smell of machines. I tsmells of the stir and sleep and waste of sixty million animals,more than half of them humans and rats. It smells of heartbreak,and the struggle to live, and of the crucial failures and l o v esthat produce our courage."
list_text = list(filter(None, text.split()))
set_text = set(list_text)

dict_text = {}
for key in set_text:
    dict_text[key] = list_text.count(key)

print(dict_text)
print()
print(f'Unique words count: {len(set_text)}. Total words count: {len(list_text)}')
